### ISSUE TITLE
Doubled horizontal lines if browser's window width is small

### ISSUE THREAD

**Issue by maxkratz** [Lithimlin/hugo-pamphlet#1]
If the browser's window width is small enough to trigger the theme to move the sidebars to the bottom, there are two vertical lines. (Only relevant if e.g. the left sidebar is empty.)

Is it possible to change this behavior to only show one horizontal line for this use case?

![Screenshot_2021-05-01_19-17-30](https://user-images.githubusercontent.com/20956405/116789929-e3a35e80-aab1-11eb-99d0-e72b55012759.png)

**Comment by Lithimlin** [comment]
Fixed with 21e0ccf!
Was easier than expected.

**Comment by Lithimlin** [comment]
Just realized that this only works on firefox.
It's currently using the `:blank` and `:-moz-only-whitespace` pseudo-class

**Comment by Lithimlin** [comment]
Should now be fixed with 4bde8a1.
